### ISSUE TITLE
Syntax highlighting broken by liquid in script tags

### ISSUE THREAD

**Issue by niedfelj** [panoply/vscode-liquid#16] opened 2019-06-14 14:29 UTC
I saw there was another issue opened about this, but I'm not sure it was clear from that one what is going on (other issue: https://github.com/panoply/vscode-liquid/issues/15)

The script block in the Debut theme is in theme.liquid, and it breaks the syntax highlighting for the rest of the file. I've attached screenshots of what it looks like after that block with and without it.

With the script block, everything after it turns blue/doesn't have highlighting.
<img width="1049" alt="Captura de Tela 2019-06-14 às 11 22 58" src="https://user-images.githubusercontent.com/294487/59516326-7ffcf180-8e97-11e9-85b1-b1ad3e3a4223.png">

Without it, it looks normal.
<img width="1024" alt="Captura de Tela 2019-06-14 às 11 23 14" src="https://user-images.githubusercontent.com/294487/59516349-84c1a580-8e97-11e9-9466-030e3c1b2888.png">

Here's the block if you want to test it

```  
  <script>
    var theme = {
      strings: {
        addToCart: {{ 'products.product.add_to_cart' | t | json }},
        soldOut: {{ 'products.product.sold_out' | t | json }},
        unavailable: {{ 'products.product.unavailable' | t | json }},
        showMore: {{ 'general.filters.show_more' | t | json }},
        showLess: {{ 'general.filters.show_less' | t | json }},
        addressError: {{ 'sections.map.address_error' | t | json }},
        addressNoResults: {{ 'sections.map.address_no_results' | t | json }},
        addressQueryLimit: {{ 'sections.map.address_query_limit_html' | t | json }},
        authError: {{ 'sections.map.auth_error_html' | t | json }}
      },
      moneyFormat: {{ shop.money_format | json }}
    }
   
   document.documentElement.className = document.documentElement.className.replace('no-js', 'js');
  </script>
```

**Comment by panoply** [comment] 2019-06-14 15:16
I an unable to recreate this issue. What's your VS Code settings look like?

**Comment by niedfelj** [comment] 2019-06-14 18:22
Ok great. Was going to say that I don't have a special config, just these extensions listed below. Let me know if you need anything else.

```
drwxr-xr-x  11 joel  staff  352 Apr 26 12:53 esbenp.prettier-vscode-1.9.0
drwxr-xr-x  16 joel  staff  512 May  3 04:39 hookyqr.beautify-1.5.0
drwxr-xr-x  11 joel  staff  352 Jan 22 11:44 mikestead.dotenv-1.0.1
drwxr-xr-x  17 joel  staff  544 Feb  7 19:47 ms-vscode.atom-keybindings-3.0.6
drwxr-xr-x  30 joel  staff  960 Feb 28 02:51 msjsdiag.debugger-for-chrome-4.11.3
drwxr-xr-x  10 joel  staff  320 Jan  8 16:08 neilding.language-liquid-0.1.1
drwxr-xr-x  14 joel  staff  448 May  3 12:53 peterjausovec.vscode-docker-0.6.2
drwxr-xr-x  15 joel  staff  480 Feb 14 13:34 robinbentley.sass-indented-1.5.1
drwxr-xr-x  15 joel  staff  480 Jun 14 11:16 sissel.shopify-liquid-1.6.5
```

**Comment by niedfelj** [comment] 2019-06-14 18:23
And yes, I have this one disabled neilding.language-liquid-0.1.1

**Comment by panoply** [comment] 2019-06-14 19:36
This in progress and should a PR will be merged over the weekend. 

The issue is actually coming from within VS Code. An error is thrown because the liquid output tags (`{{ .. }}`) used in your `var theme` are being treated as objects as I mentioned in #15 – The only solution I can see moving forward is writing a pattern to match liquid output tags within javascript.

**Closed** 2019-06-16 05:32 UTC
Labels: Extension Bug

**Comment by panoply** [comment] 2019-06-16 05:45
@niedfelj Update to version 1.7.0 and everything should work as expected

**Comment by niedfelj** [comment] 2019-06-16 14:08
Looks amazing, thank you!
