### ISSUE TITLE
Formatter removes newlines in a weird way

### ISSUE THREAD

**Issue by georgeonofrei** [panoply/vscode-liquid#7] opened 2019-04-23 08:55 UTC
Hi,

I've just isntalled your extension into VSCode and like how it works so far.
One issue I have is with the formatter with the default settings -> it removes my newlines .
Example:
1. code
```
{%- comment -%}
make sure this file does not have any additional new lines in it. it would break calss generation

assumed variables:
- genClass
- genAdditionalClass
- genSectionClass
- genUseNarrow
{%- endcomment -%}
{%- assign container-classes = bgt-block-h-text-image.container-class | split: ' ' -%}
{%- assign additional-container-classes = additionalContainerClass | split: ' ' -%}
{%- assign containerClass = 'bgt-component-section-h-text-image' -%}
{%- assign isNarrow = true -%}
{%- for class in additional-container-classes -%}
{%- assign containerClass = containerClass | append: ' bgt-component-section-h-text-image--' | append: class -%}
{%- assign containerClass = containerClass | append: ' bgt-component-section--' | append: class -%}
{%- if class == 'edge-to-edge' or class == 'full-width' -%}
{%- assign isNarrow = false -%}
{%- endif -%}
{%- endfor -%}
```

2. first save
```
{% comment %}{%- comment -%}{% endcomment %}
make sure this file does not have any additional new lines in it. it would break calss generation

assumed variables:
- genClass
- genAdditionalClass
- genSectionClass
- genUseNarrow{%- endcomment -%}{%- assign container-classes = bgt-block-h-text-image.container-class | split: ' ' -%}{%- assign additional-container-classes = additionalContainerClass | split: ' ' -%}{%- assign containerClass = 'bgt-component-section-h-text-image' -%}{%- assign isNarrow = true -%}{%- for class in additional-container-classes -%}
{%- assign containerClass = containerClass | append: ' bgt-component-section-h-text-image--' | append: class -%}
{%- assign containerClass = containerClass | append: ' bgt-component-section--' | append: class -%}
{%- if class == 'edge-to-edge' or class == 'full-width' -%}
    {%- assign isNarrow = false -%}
{%- endif -%}{%- endfor -%}
```

3. second save
```
{% comment %}{%- comment -%}{% endcomment %}make sure this file does not have any additional new lines in it. it would break calss generation
    
    assumed variables:
    - genClass
    - genAdditionalClass
    - genSectionClass
    - genUseNarrow{%- endcomment -%}{%- assign container-classes = bgt-block-h-text-image.container-class | split: ' ' -%}{%- assign additional-container-classes = additionalContainerClass | split: ' ' -%}{%- assign containerClass = 'bgt-component-section-h-text-image' -%}{%- assign isNarrow = true -%}{%- for class in additional-container-classes -%}{%- assign containerClass = containerClass | append: ' bgt-component-section-h-text-image--' | append: class -%}{%- assign containerClass = containerClass | append: ' bgt-component-section--' | append: class -%}{%- if class == 'edge-to-edge' or class == 'full-width' -%}
{%- assign isNarrow = false -%}{%- endif -%}{%- endfor -%}
```

As you can see above, new lines are removed one by one after multiple saves and the code gets minified to some degree. What I want is to automatically indent the code so that I can better follow statements.

I have disabled the formatter as it does not help me at all.

Thanks,
George

**Comment by panoply** [comment] 2019-04-23 16:41
Hey @georgeonofrei the formatter uses [PrettyDiff](http://prettydiff.com) which has trouble formatting whitespace  liquid comments which are comments that use dash syntax, eg: `{%- comment -%}`. By default any `{% comment %}` or {%- comment -%} tags are ignored, it's a small price to pay until the issue is resolved by PrettyDiff.  

I documented ignored tags [here](https://github.com/panoply/vscode-liquid#formatting). If you can share with me your custom settings it would give me more insight into why the comment tags are not being ignored. Below is a test of your above code with the default settings:

![screencast 2019-04-23 18-34-52](https://user-images.githubusercontent.com/7041324/56599670-517d3b80-65f7-11e9-90e7-ba988a864ff0.gif)

**Comment by panoply** [comment] 2019-04-23 21:43
Issue has been submitted [here](https://github.com/prettydiff/prettydiff/issues/586) regarding this defect within the parser.

**Closed** 2019-04-24 23:31 UTC
Labels: bug

**Comment by panoply** [comment] 2019-04-24 23:34
@georgeonofrei version 1.6.2 fixes this issue, update the extension and everything should work as expected.
