### ISSUE TITLE
Incorrect comment blocks in Liquid files with this extension enabled

### ISSUE THREAD

**Issue by t3pfaffe** [panoply/vscode-liquid#119] opened 2022-10-18 20:21 UTC
Using the keybind `ctrl+/` to generate a new comment block erroneously produces a string of characters (`{%\s*# `) instead of the expected `{% comment %} {% endcomment %}`. I previously had the extension [Liquid Comments](https://marketplace.visualstudio.com/items?itemName=chris-hayes.liquid-comments) enabled although this issue appears to happen regardless of that being enabled. The issue only occurs when this liquid extension is enabled. This issue has only started happening in the last day.

I have not changed my VSCode configuration in that time outside of a VSCode update/restart and I don't think there has been any new updates from this extension.

**Comment by icantrank** [comment] 2022-10-24 16:03
This is also happening to me with `.css.liquid` files using the `liquid-css` language and `ctrl+/` hotkey.
I would usually expect `/* */` but I get this `{%\s*#` instead.

**Comment by ArturoDent** [comment] 2022-10-24 21:27
Until this issue is fixed, I posted a workaround at [SO: [VSCode not commenting css.liquid lines correctly](https://stackoverflow.com/questions/74181082/vscode-not-commenting-css-liquid-lines-correctly)](https://stackoverflow.com/a/74186897/836330)

![liquidComments](https://user-images.githubusercontent.com/31813701/197632483-ed3d68c7-ebc3-4909-b5c7-c69f9cd5cbad.gif)

I am not familiar with liquid comment styles so let me know if something needs to be changed.

**Comment by panoply** [comment] 2022-10-25 04:30
Hey guys, 

This one is on me. It seems I added an expression in the language configuration. I'll apply a patch later today for this.

**Comment by FHoogland** [comment] 2022-10-26 09:19
@panoply Hey, this issue seems to have been fixed in one of my projects but still persists in another project. Is there any extension-setting I should change for the fix to take effect?

**Comment by panoply** [comment] 2022-10-27 09:49
Shipping this today. Sorry, I have been sick last couple of days.

**Comment by FHoogland** [comment] 2022-10-27 09:50
No worries, was just wondering if I was doing something wrong. Hope you feel better soon!

**Closed** 2022-10-27 10:17 UTC
Labels: Bug, ⚠️ Monitoring

**Comment by panoply** [comment] 2022-10-27 10:20
🚢 Shipped - Update and reload vscode everything should work as intended.
